// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VideoGameApi.Data;

#nullable disable

namespace VideoGameApi.Migrations
{
    [DbContext(typeof(VideoGameDbContext))]
    [Migration("20250515043303_seeding")]
    partial class seeding
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("VideoGameApi.VideoGame", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Developer")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Platform")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Publisher")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("VideoGames");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Developer = "Nintendo EPD",
                            Platform = "Nintendo Switch",
                            Publisher = "Nintendo",
                            Title = "The Legend of Zelda: Breath of the Wild"
                        },
                        new
                        {
                            Id = 2,
                            Developer = "CD Projekt Red",
                            Platform = "PC, PS4, Xbox One, Nintendo Switch",
                            Publisher = "CD Projekt",
                            Title = "The Witcher 3: Wild Hunt"
                        },
                        new
                        {
                            Id = 3,
                            Developer = "Santa Monica Studio",
                            Platform = "PS4, PC",
                            Publisher = "Sony Interactive Entertainment",
                            Title = "God of War"
                        },
                        new
                        {
                            Id = 4,
                            Developer = "FromSoftware",
                            Platform = "PC, PS4, Xbox One, Nintendo Switch",
                            Publisher = "Bandai Namco Entertainment",
                            Title = "Dark Souls III"
                        },
                        new
                        {
                            Id = 5,
                            Developer = "Team Cherry",
                            Platform = "PC, PS4, Xbox One, Nintendo Switch",
                            Publisher = "Team Cherry",
                            Title = "Hollow Knight"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
